--Inserir Registros Comunidade

INSERT INTO Comunidade (idComunidade, nome, estado, descricao, cidade, caracteristicasGeograficas, tipoArea, id_Conta)
VALUES
	(1, 'Quilombo urbano Namastê','Minas Gerais', 'A comunidade Namastê, certificado como remanescente de quilombo pela Fundação Cultural Palmares, surgiu em 1836, com pessoas vítimas da Fazenda da Liberdade.  No local , parte das ações do quilombo são atualmente fundamentadas por um terreiro de Umbanda. À medida que o espaço foi ganhando novos habitantes, transformou-se em um bairro mais de um século depois — levando à perda do senso de comunidade e parte da ancestralidade que os unia. Para a líder da comunidade e mestre dos saberes Maria Luiza Marcelino, o local urbano tira a individualidade das ações de políticas públicas, tornando-se um novo desafio. Atualmente, o quilombo Namastê concentra cerca de 300 famílias. Suas expressões culturais são vastas, incluindo o teatro quilombola, capoeira, jongo, maculelê, danças afro-brasileiras, saberes sobre ervas medicinais e uma escola de samba.', 
		'Ubá', 'Rua José Lourenço da Silva, 310', 'Urbana', 21),
	(2, 'Aldeia Apiwtxa', 'Acre', 'A Aldeia Apiwtxa, comunidade originária dos Incas Peruanos, é habitada por cerca de 800 pessoas do Povo Ashaninka, pertencente à família linguística Aruak. A história da aldeia e do povo Ashaninka é marcada por um histórico de luta e desafios como a exploração predatória de madeira, a invasão de madeireiras peruanas, disputa pelo reconhecimento do valor dos seus conhecimentos e dificuldade para acessar políticas públicas fundamentais (como educação e saúde). Em território nacional, os Ashaninka estão em Terras Indígenas distintas e descontínuas, todas situadas na região do Alto Juruá.',
		'Marechal Thaumaturgo', 'Terra Indígena Kampa do Rio Amônia, próximo a fronteira do Brasil com Peru', 'Rural', 22),
	(3, 'Etnia krenak', 'Minas Gerais', 'Composto por 8 aldeias, O povo Krenak sofreu diversas violações e expropriações culturais e territoriais desde o período colonial. Na história oficial, o Reformatório Krenak, instalado pelo governo militar, foi palco de espancamento, tortura e desaparecimentos. Dessa forma, com o histórico de genocídio, atualmente vivem em uma área reduzida, reconquistada com grandes dificuldades. Ganharam visibilidade com a tragédia de Mariana, em 2015, onde toda a vegetação e fauna do Rio Doce foram devastadas, a principal fonte de subsistência dos krenak. Ailton Krenak é um de seus mais destacados líderes que vem lutando pela causa indígena há décadas. Foi o responsável pelo discurso emblemático no Congresso Nacional, em 1987, onde pintou o rosto de preto em sinal de luto, gerando intensa repercussão e contribuindo para a inclusão dos direitos indígenas na Constituição de 1988.',
		'Resplendor', 'Área Médio do Rio Doce', 'Rural',  16),
	(4, 'Povo Guajajara/Tentehar', 'Maranhão', 'Os Guajajara, da família linguística Tupi-Guarani, são um dos povos indígenas mais numerosos do Brasil, presentes em mais de 10 Terras Indígenas na margem oriental da Amazônia. Eles sobrevivem da agricultura de subsistência e da venda de artesanatos, possuindo autodenominação Tenetehara (“Gente de verdade”, na língua materna). Com um histórico de demarcações e invasões de suas terras, ainda enfrentam dificuldades na manutenção e preservação da integridade de seus territórios, mesmo que atualmente sejam reconhecidos. São aldeias que vivem em situações vulneráveis, com ausência de políticas públicas essenciais, como a segurança.',
		'Pindaré-Mirim', 'Terra Indígena Araribóia, entre as cidades de Amarante, Grajaú e Santa Luzia', 'Rural' , 17),
	(5, 'Quilombo Nossa Senhora do Rosário de Justinópolis', 'Minas Gerais', 'Fundada em meados de 1891 por um pequeno grupo que se reunia para dançar o Candombe, uma dança de origem africana, a Irmandade Nossa Senhora do Rosário de Justinópolis rapidamente cresceu e se transformou em uma organização social quilombola unida por objetivos comuns de vida, sendo reconhecida somente em 2015 como um quilombo pelo governo. Com uma história profundamente enraizada na resistência e na luta pela liberdade e contra o preconceito, ainda enfrenta desafios, como a falta de comunicação com o poder público, ataques de violência, intolerância religiosa e a perda de território.  Atualmente, conta com cerca de noventa famílias cadastradas, totalizando mais de trezentos quilombolas',
		'Ribeirão das Neves', 'Rua Francisco Labanca, 189, bairro Justinópolis', 'Rural', 18),
	(6, 'Quilombo Buieié',  'Minas Gerais', 'Certificado como remanescente de quilombo pela Fundação Cultural Palmares, no território vivem 100 famílias quilombolas e outras 30 que compraram terras e hoje residem. Com uma trajetória de resistência e liderança feminina, o Buieié Projeto Social foi fundado. Criado como forma de resistência às opressões vividas, empoderamento, apropriação da sua história, geração de renda local através da produção de alimentos e artesanato, além de incentivar a juventude a estudar e adentrar as universidades públicas, dar visibilidade a cultura local e denunciar as precariedades e mazelas que o poder público municipal tem deixado à comunidade, englobando várias outras atividades.',
		'Viçosa', 'Região da Violeira – próximo ao CTA – Centro de Tecnologias Alternativas da Zona da Mata, a 10km de distância do centro da cidade de Viçosa.', 'Rural', 19),
	(7, 'Quilombo Barra da Aroeira', 'Tocantins', 'Formada em meados da década de 30, a comunidade reúne cerca de 97 famílias que produzem de tudo um pouco: arroz, feijão, mandioca, abóbora, inhame, batata-doce, hortaliças, galinha, porcos. A Associação Comunitária do Quilombo da Barra da Aroeira é comandada por Maria de Fátima Rodrigues, de 50 anos, sendo primeira mulher a presidir a associação. O modo de produção da comunidade da Barra da Aroeira segue os princípios da agroecologia. Maria de Fátima compartilha que o principal desafio da comunidade é conseguir apoio para aumentar a produção e, consequentemente, a renda.',
		'Santa Tereza', 'Localizado cerca de 160km de Natal', 'Rural', 20);




